### ISSUE TITLE
Уточнения по тестам - зацепить библиотеку testify

### ISSUE THREAD

**Issue by comdiv** [TeacherKPIDevTeam/TeacherKPI#4]
https://github.com/stretchr/testify

де-факто стандарт для тестов в голанг, даром что внешний пакет

тесты в main_test переписать так, чтобы вместо "в лоб" проверки условий и `t.Error` использовать
`assert.***` или `require.***` из пакета `testify`

**Comment by DelecD** [comment]
Заметил, что коммит не прошел тест на гитхабе

**Comment by DelecD** [comment]
Отказывался собираться из-за неправильной версии в yml конфиге

**Comment by comdiv** [comment]
Вот сейчас да, чистенько
